name: Test Project
on: push
jobs:
    fetch-code:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
    install-terraform:
        runs-on: ubuntu-latest
        steps:
            - name: Install terraform
              uses: hashicorp/setup-terraform@v3
            - name: Verify terraform installation
              run :
                terraform -help
    deploy-terraform-infra:
        runs-on: ubuntu-latest
        steps:
            - name: Run terraform
              run: terraform apply