name: Test Project
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Show dir1
              run : |
                pwd
                ls -lrt
            - name: Get Code
              uses: actions/checkout@v4
            - name: Show dir2
              run : |
                pwd
                ls -lrt
            - name: Install terraform
              uses: hashicorp/setup-terraform@v3
            - name: Verify terraform installation
              run :
                terraform -help
            - name: Show dir3
              run : |
                pwd
                ls -lrt


              


              
