name: Test Project
on: [push, workflow_dispatch]
env: 
    AWS_ACCESS_KEY_ID: "${{secrets.AWS_ACCESS_KEY_ID}}"
    AWS_SECRET_ACCESS_KEY: "${{secrets.AWS_SECRET_ACCESS_KEY}}"
    AWS_DEFAULT_REGION: "${{secrets.AWS_DEFAULT_REGION}}"
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install dependencies
              run:
                pip install pandas
            - name: Run Test
              run:
                python test.py

    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install terraform
              uses: hashicorp/setup-terraform@v3
            - name: Verify terraform installation
              run :
                terraform -help
            - name: list files
              run: |
                pwd
                ls -lart
            - name: configure-awscli
              run: |
                 aws --version
                 aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
                 aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
                 aws configure set region $AWS_DEFAULT_REGION
                 aws configure list
            - name: Create terraform infra
              run: |
                terraform init
                terraform apply -auto-approve
            - name: Get EC2 Ip
              run: 
                echo "public ip = $(terraform output -raw myEc2Ip)"
            - name: wait for ec2 to be ready
              run: sleep 120
            - name: ssh to ec2
              run: |
               chmod 400 my-ec2-key.pem
               ssh -o StrictHostKeyChecking=no -i "my-ec2-key.pem" ubuntu@$(terraform output -raw myEc2Ip)
               git clone https://github.com/VaderKB/gh-first-action.git
               cd gh-first-action
               ls -lrt
               sudo apt update
               sudo apt install -y apache2
               sudo mv website.html /var/www/html/index.html
               sudo systemctl restart apache2
            - name: Install dependencies
              run:
                pip install pandas
            - name: Run Test
              run:
                python test.py
            - name: Destroy infra
              if: always()
              run: terraform destroy -auto-approve

