name: Test Project
on: push
env: 
    AWS_ACCESS_KEY_ID: "${{secrets.AWS_ACCESS_KEY_ID}}"
    AWS_SECRET_ACCESS_KEY: "${{secrets.AWS_SECRET_ACCESS_KEY}}"
    AWS_DEFAULT_REGION: "${{secrets.AWS_DEFAULT_REGION}}"
jobs:
    fetch-code:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install terraform
              uses: hashicorp/setup-terraform@v3
            - name: Verify terraform installation
              run :
                terraform -help
            - name: list files
              run: |
                pwd
                ls -lart
            - name: configure-awscli
              run: |
                 aws --version
                 aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
                 aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
                 aws configure set region $AWS_DEFAULT_REGION
                 aws configure list
            - name: Run terraform
              run: |
                terraform init
                terraform apply -auto-approve
            - name: Install dependencies
              run:
                pip install pandas
            - name: Run Test
              run:
                python test.py
