name: Test Project
on: push
jobs:
    fetch-code:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install terraform
              uses: hashicorp/setup-terraform@v3
            - name: Verify terraform installation
              run :
                terraform -help
            - name: list files
              run: |
                pwd
                ls -lart
            - name: Run terraform
              run: terraform apply -auto-approve
    aws-infra:
        runs-on: ubuntu-latest
        steps:
            - name: install-awscli
              uses: unfor19/install-aws-cli-action@v1
            - name: test-awscli
              run: aws