name: Test Project
on: push
env: 
    AWS_ACCESS_KEY_ID: "${{secrets.AWS_ACCESS_KEY_ID}}"
    AWS_SECRET_ACCESS_KEY: "${{secrets.AWS_SECRET_ACCESS_KEY}}"
    AWS_DEFAULT_REGION: "${{secrets.AWS_DEFAULT_REGION}}"
jobs:
    fetch-code:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install terraform
              uses: hashicorp/setup-terraform@v3
            - name: Verify terraform installation
              run :
                terraform -help
            - name: list files
              run: |
                pwd
                ls -lart
            - name: Run terraform
              run: terraform apply -auto-approve
    aws-infra:
        runs-on: ubuntu-latest
        steps:
            - name: configure-awscli
              run: |
                 aws --version